### ISSUE TITLE
Index (2) out of range in line 486

### ISSUE THREAD

**Issue by bxkg** [SebastienTs/MosaicExplorerJ#1]
files named correctly in subfolders, but keep getting this error

**Comment by SebastienTs** [comment]
It seems related to either the incorrect setting of dual camera / dual side option, or the incorrect detection of the XY dimension of the tile grid. It is quite hard to say without the dataset. Could you maybe share a cropped version of the dataset with few Z slices with me, or at least send me a snapshot of the folder/file organization so that I can check it?

**Comment by bxkg** [comment]
Thank you for your reply. I was missing a second dash in the file naming, my mistake.
